name: Build github io master
on:
  push:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build
        run: npm run build
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@releases/v3
